---
- name: install nginx
  ansible.builtin.apt:
    pkg: "{{ nginx_pkgs }}"
    state: present
  notify: 
    - Start Nginx   

- name: Copy file nginx@.service
  ansible.builtin.copy:
    src: nginx@.service
    dest: "{{ nginx_service }}"
    owner: root
    group: root
    mode: '0644'

- name: Create file with variables for unit
  ansible.builtin.template:
    src: nginx-.conf.j2
    dest: "/etc/nginx/nginx-{{ item.name }}.conf"
    backup: true
  loop: "{{ nginx_conf }}"

- name: Enable and start services
  ansible.builtin.service:
    name    : "nginx@{{ item.name }}"
    state   : started
  loop: "{{ nginx_conf }}"
  notify: 
    - Restart Nginx
...